#!/usr/bin/env node
/**
 * BUILD APPS — bundles every app's `client.js` (whose `manifest.quapp`
 * declares a `clientMain`) into a fully self-contained
 * `apps/<name>/dist/client.js`, gitignored build output regenerated by
 * `npm run build`.
 *
 * "Fully self-contained" is the whole reason this script exists at all, not
 * a nice-to-have: bare imports like `@qu/i18n`/`@qu/ui`/`@qu/services` don't
 * resolve in a raw browser (no import map, no bundler on the serving side -
 * `@qu/relay`'s `static-apps.js` just serves whatever bytes are on disk) -
 * bundling with `bundle: true` and leaving `@qu/*` un-external inlines every
 * workspace dependency an app's `client.js` imports.
 *
 * Deliberately scoped down from a "bundle every package" build (what a
 * future `@qu/loader` remote-publishing workflow will eventually need):
 * this round's real, immediate need is exactly "the apps under `apps/*`
 * that ship a browser half can actually load in a browser" - nothing under
 * `packages/*` is remote-loaded yet, so there is nothing there to bundle
 * ahead of a real caller. Grows into that once `@qu/loader`'s `loadRemote()`
 * needs a self-contained `dist/index.min.js` per package for real.
 *
 * `apps/shell` also gets bundled here, UNCONDITIONALLY (no `manifest.quapp`
 * gate - it has none, see `apps/shell/client.js`'s own doc comment for why
 * it isn't a `@qu/loader`-discovered app at all) into
 * `apps/shell/dist/shell-bundle.js` - the fixed name `@qu/relay`'s
 * `static-shell.js` serves at `/shell-bundle.js`.
 *
 * `apps/shell/sw.js` (the PWA update-flow service worker, see that file's
 * own doc comment) also gets stamped here: it's plain, unbundled JS (no
 * `@qu/*` import for esbuild to resolve), so it doesn't go through
 * `buildApp()` - instead its one `__SW_VERSION__` placeholder is replaced
 * with a short hash of the JUST-BUILT `shell-bundle.js`'s own bytes, and
 * the result is written to `apps/shell/dist/sw.js`. Tying the version to
 * the shell bundle's actual content (not a hand-maintained counter, unlike
 * the prototype this is rebuilt from) means a browser reliably notices a
 * new service worker on every real deploy, and notices NOTHING on a build
 * that changed nothing - no discipline required to remember bumping it.
 */
import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, access } from 'node:fs/promises';
import { join } from 'node:path';
import esbuild from 'esbuild';

const ROOT = new URL('..', import.meta.url).pathname;
const APPS_DIR = join(ROOT, 'apps');
const SHELL_DIR = join(APPS_DIR, 'shell');

/**
 * `manifest.quapp`'s own `clientMain` field is the SERVED path (e.g.
 * `"./dist/client.js"` - what `@qu/relay`'s `apps-catalog.js` resolves into
 * a URL a shell loads), not the source this script compiles FROM - same
 * convention QuV2 used. The source this script reads is always the fixed,
 * un-bundled `<appDir>/client.js` sitting next to the manifest; only apps
 * whose manifest actually declares a `clientMain` (i.e. ships a browser
 * half at all - see apps/forum's server-only manifest for the alternative)
 * get built.
 */
async function findClientApps() {
  let entries;
  try {
    entries = await readdir(APPS_DIR, { withFileTypes: true });
  } catch {
    return [];
  }
  const apps = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const manifestPath = join(APPS_DIR, entry.name, 'manifest.quapp');
    let manifest;
    try {
      manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
    } catch {
      continue; // no manifest.quapp (or invalid JSON) - not a loadable app, nothing to bundle
    }
    if (!manifest.clientMain) continue; // server-only app (e.g. apps/forum) - nothing to bundle
    apps.push({ name: entry.name, dir: join(APPS_DIR, entry.name) });
  }
  return apps;
}

async function buildApp({ name, dir }, outname = 'client.js') {
  const entry = join(dir, 'client.js');
  const outfile = join(dir, 'dist', outname);
  await esbuild.build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    minify: true,
    sourcemap: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    logLevel: 'warning',
  });
  console.log(`  ${name} -> ${outfile.replace(ROOT, '')}`);
}

async function shellExists() {
  try {
    await access(join(SHELL_DIR, 'client.js'));
    return true;
  } catch {
    return false;
  }
}

/** See this file's own doc comment on `apps/shell/sw.js`'s `__SW_VERSION__` stamping. */
async function stampServiceWorker() {
  let source;
  try {
    source = await readFile(join(SHELL_DIR, 'sw.js'), 'utf8');
  } catch {
    return; // no apps/shell/sw.js yet - nothing to stamp
  }
  const bundle = await readFile(join(SHELL_DIR, 'dist', 'shell-bundle.js'));
  const version = createHash('sha256').update(bundle).digest('hex').slice(0, 16);
  const outfile = join(SHELL_DIR, 'dist', 'sw.js');
  await writeFile(outfile, source.replace('__SW_VERSION__', version));
  console.log(`  sw.js -> ${outfile.replace(ROOT, '')} (${version})`);
}

console.log('Building apps...');
const apps = await findClientApps();
if (apps.length === 0) {
  console.log('  (no app under apps/* declares a clientMain yet)');
} else {
  for (const app of apps) await buildApp(app);
}

if (await shellExists()) {
  await buildApp({ name: 'shell', dir: SHELL_DIR }, 'shell-bundle.js');
  await stampServiceWorker();
} else {
  console.log('  (no apps/shell/client.js yet - nothing to bundle)');
}
